export default {
  participants: [
    'Joren',
    'Gerjan',
    'Alexandre',
    'Fevzi',
    'Jeff',
    'Sumeet',
    'Beytun',
    'Rahul',
    'Pavan',
    'Hrishikesh',
    'Ioannis',
    'Sunil',
    'Yogesh',
    'Rick',
    'Shilpi',
    'Dhirendra',
    'Cigdem',
    'Keerthana',
    'Danny',
    'Hans',
  ],
  title: 'JavaScript workshop',
  usingParticipantIframes: false,
  alwaysServeFiles: true,
};
